### ISSUE TITLE
tyaml displaying empty line

### ISSUE THREAD

**Issue by calebe94** [Calebe94/pytools#115]
Given the following file:

* test.yml

```yaml
parentKey:
  child1: some value
  child2: foo
  child3: bar
    childAgain: test
    anotherChild: more value
  child3: something
```

When running the following command, the script prints an empty line:

```bash
$ tyaml tmenu/arquivo.yaml -k parentKey.child3
```

The output is: 

```

childAgain
anotherChild
```

Note that `tyaml` is showing 3 results, one of them is empty. 

A possible solution will be add an `awk` at the last `echo` of the script:

```
echo $output | awk /./
```
